# A sample Gemfile
source "https://rubygems.org"

# gem "rails"
#
# source 'http://gemcutter.org'
# source 'http://gemcutter.org'
# source 'http://gems.github.com'
# source 'http://gems.rubyforge.org

gem 'rspec'
gem 'watir-webdriver'
gem 'page-object'
